### PR TITLE
Repair mkdir on Windows

### PR DESCRIPTION
**Pull request by Creator-Lin**

### CODE REVIEW

**Comment by occivink** [comment]
Can you elaborate, what's wrong with just using `'mkdir', thumbs_dir`?

**Comment by Creator-Lin** [comment]
After testing on Windows 10 22H2, the thumbs_dir couldn't be created without `playback_only = false` and `args = { "cmd", "/C", "mkdir " .. thumbs_dir }`. Did you test just using the `args = { 'mkdir', thumbs_dir }` on Windows? and could the thumbs_dir be created?

**Comment by occivink** [comment]
I don't have a way to test on windows so I do not know if the previous implementation was at all functional. The `playback_only = false` change makes total sense, the `name = "subprocess"` does not I think, the `"cmd ", "/C"` one I'm not sure

**Comment by Creator-Lin** [comment]
Hi occivink!
I have found [this](https://github.com/mpv-player/mpv/issues/6883) in the mpv project which could do help to the use of `utils.subprocess` on windows.
Maybe this could explain why to use `cmd` and `/c` args on windows.(As powershell are similar to cmd on windows and echo and mkdir are both basic command on windows.)
By the way, the name arg was not a matter, as using `utils.subprocess` would automatically set the name arg to subprocess just as what mentioned in the offical mpv document.
Best Regards.

**Pull request closed without merging**
